name: DNA Evolve
favicon: null
layout_spectrum: 0.24204
typography_spectrum: 0.50503
title: Ascension Nootropic
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#423aa5'
    - '#7989e9'
    - '#040208'
    - '#5a5e7e'
    - '#e3e9fe'
  brandStrength: 1
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
