name: DNA Evolve
favicon: null
layout_spectrum: 0.24204
typography_spectrum: 1
title: Ascension Nootropic
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#162744'
    - '#00e232'
    - '#7d7dbf'
    - '#ed7500'
  brandStrength: 0.5
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
